<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageRoles.aspx.cs" Inherits="polymer_Web_ERP_V4.Roles.ManageRoles" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <b>Create a New Role: </b>
    <asp:TextBox ID="RoleName" runat="server"></asp:TextBox>

    <asp:RequiredFieldValidator ID="RoleNameReqField" runat="server" 
            ControlToValidate="RoleName" Display="Dynamic" 
            ErrorMessage="You must enter a role name."></asp:RequiredFieldValidator>
        
        <br />

    <br />
    <asp:Button ID="CreateRoleButton" runat="server" Text="Create Role" OnClick="CreateRoleButton_Click" />

    <%--I prefer to explicitly define my columns rather than have them implicitly generated by the GridView--%>

    <%--The array's contents are displayed using the databinding syntax <%# Container.DataItem %>. 
    A thorough description of why this syntax is used when displaying the contents of an array bound to the GridView is beyond the scope of this tutorial. 
    For more information on this matter, refer to Binding a Scalar Array to a Data Web Control.--%>
    <br />

    <p>
        <asp:GridView ID="RoleList" runat="server" AutoGenerateColumns="False" onrowdeleting="RoleList_RowDeleting">
            <Columns>
                <asp:CommandField DeleteText="Delete Role" ShowDeleteButton="True" />
                <asp:TemplateField HeaderText="Role">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="RoleNameLabel" Text='<%# Container.DataItem %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                
            </Columns>

        </asp:GridView>
    </p>

</asp:Content>
