//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace polymer_Web_ERP_V4.BusinessLayer.Monitoring
{


    public partial class temperatureMonitoring
    {
    }
}
